# Generated by Django 3.0.4 on 2020-04-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtec', '0002_auto_20200402_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
