# Generated by Django 3.0.4 on 2020-04-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
